# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0

name: Python Lint

on:
  pull_request:
    branches:
    - main
    paths:
      - 'src/**'
      - 'tox.ini'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    uses: outpost-os/pipeline-python/.github/workflows/lint.yml@v1
    with:
      python-version: '3.10'
